"""add language to posts

Revision ID: 84387fcb7478
Revises: 885b0f1156be
Create Date: 2023-12-26 16:40:22.396760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84387fcb7478'
down_revision = '885b0f1156be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
